spring:
    datasource:
        url: jdbc:postgresql://localhvzgzgost:5432/default_database
        username: username
        password: password
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true # Pour afficher les requ?tes SQL dans la console
        hibernate:
            ddl-auto: validate # Pour que Spring cr?er le sch?ma en lan?ant les migrations

springdoc:
    swagger-ui.path: /api
    api-docs.path: /api/doc

logging.level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    fr.ulco: DEBUG

jwt:
    secret: "mysecretkey"